@ECHO OFF

ECHO ===========================================================================
ECHO CMD EXECUTION 1
ECHO Command Line Interface commands run by admin@338 APT GROUP
ping -n 3 127.0.0.1 > NUL

echo d76261ba3b624933a6ebb5dd73758db4 > C:\\Users\\test.sandbox\\AppData\\Local\\Temp\\time.exe
echo d76261ba3b624933a6ebb5dd73758db4 > C:\\Users\\test.sandbox\\AppData\\Local\\Temp\\WmiApCom
echo 79b68cdd0044edd4fbf8067b22878644 > C:\\Users\\test.sandbox\\AppData\\Local\\Temp\\WmiApCom.bat
type C:\\Users\\test.sandbox\\AppData\\Local\\Temp\\WmiApCom.bat
echo \"backdoor commands\" > C:\\Users\\AUTOMA~1\\AppData\\Local\\Temp\\computername_upload.bat
